services:
  hive-dashboard:
    image: hive-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    environment:
      NODE_URL: http://localhost:3001
    ports:
      - "8000:80"
